In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(3,)

In [5]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
array.shape

(3, 3)

In [7]:
array.ndim

2

In [8]:
array.size

9

In [9]:
array.dtype

dtype('int64')

In [10]:
arr = np.zeros((1, 3))
arr

array([[0., 0., 0.]])

In [11]:
arr = np.ones((4, 3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr = np.arange(0, 10, 2)
arr

array([0, 2, 4, 6, 8])

In [13]:
arr = np.linspace(0, 1, 5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
arr = np.random.rand(3, 3)
arr

array([[0.4762471 , 0.57981943, 0.32268413],
       [0.90168665, 0.50701781, 0.97968321],
       [0.23270793, 0.76136169, 0.17122361]])

In [15]:
arr

array([[0.4762471 , 0.57981943, 0.32268413],
       [0.90168665, 0.50701781, 0.97968321],
       [0.23270793, 0.76136169, 0.17122361]])

In [16]:
arr.astype(np.complex64)

array([[0.4762471 +0.j, 0.57981944+0.j, 0.32268414+0.j],
       [0.90168667+0.j, 0.5070178 +0.j, 0.9796832 +0.j],
       [0.23270793+0.j, 0.7613617 +0.j, 0.17122361+0.j]], dtype=complex64)

In [17]:
arr = np.arange(0, 10, 2)
arr

array([0, 2, 4, 6, 8])

In [18]:
len(arr)

5

In [19]:
arr[2]

np.int64(4)

In [20]:
arr[0:3]

array([0, 2, 4])

In [21]:
arr[arr >= 2]

array([2, 4, 6, 8])

In [22]:
np.sum(arr)

np.int64(20)

In [23]:
np.min(arr),  np.max(arr), np.average(arr)

(np.int64(0), np.int64(8), np.float64(4.0))

In [24]:
arr = np.array([1, 2, 3, 4])
arr * 2

array([2, 4, 6, 8])

In [25]:
arr = list([1, 2, 3, 4])
type(arr)

list

In [26]:
arr * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [29]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

a * b, a + b

(array([ 5, 12, 21, 32]), array([ 6,  8, 10, 12]))

In [30]:
np.dot(a, b)

np.int64(70)

In [39]:
np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr.shape

(3, 3)

In [36]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
np.split(arr, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [41]:
arr.sum(axis=0)

array([12, 15, 18])

In [42]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [43]:
np.random.seed(42)
print(np.random.randint(0, 10, 5))

[6 3 7 4 6]


In [44]:
np.random.seed(42)
print(np.random.randint(0, 10, 5))

[6 3 7 4 6]


In [45]:
print(np.random.randint(0, 10, 5))

[9 2 6 7 4]


In [46]:
print(np.random.randint(0, 10, 5))

[3 7 7 2 5]


In [51]:
arr = np.array([1, 2, 3, 4, 5])

mask = arr % 2 != 0

arr[mask]

array([1, 3, 5])