In [1]:
import torch

In [2]:
arr = torch.tensor([1, 2, 3])
arr

tensor([1, 2, 3])

In [3]:
arr.dtype

torch.int64

In [6]:
a = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0], [3, 5, 1, 6, 0]])

In [7]:
a

tensor([[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0],
        [3, 5, 1, 6, 0]])

In [9]:
a.size()

torch.Size([3, 5])

In [11]:
torch.zeros((2, 2))

tensor([[0., 0.],
        [0., 0.]])

In [12]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
torch.empty((4, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
torch.rand((5, 5))

tensor([[0.4683, 0.9399, 0.2043, 0.3192, 0.4372],
        [0.6644, 0.1833, 0.1421, 0.5662, 0.6293],
        [0.2060, 0.1599, 0.8967, 0.2549, 0.4301],
        [0.3930, 0.4052, 0.2242, 0.2581, 0.7768],
        [0.0175, 0.3746, 0.5983, 0.2430, 0.6177]])

In [16]:
torch.randn((3, 3))

tensor([[ 1.3373, -1.6333,  0.4542],
        [ 0.4991,  0.0659,  0.1533],
        [-0.8791,  1.8459,  1.0724]])

In [17]:
torch.arange(0, 10, 3)

tensor([0, 3, 6, 9])

In [19]:
import numpy as np 

In [20]:
b = np.array([1, 2, 3])

In [23]:
type(b)

numpy.ndarray

In [24]:
c = torch.from_numpy(b)

In [25]:
type(c)

torch.Tensor

In [26]:
d = c.numpy()

In [27]:
type(d)

numpy.ndarray

In [30]:
torch.zeros_like(c)

tensor([0, 0, 0])

In [31]:
torch.ones_like(c)

tensor([1, 1, 1])

In [32]:
a = torch.rand((3, 3))
a

tensor([[0.3853, 0.0874, 0.2020],
        [0.1792, 0.9252, 0.3442],
        [0.1759, 0.4542, 0.2697]])

In [34]:
a.shape, a.size(), a.dtype

(torch.Size([3, 3]), torch.Size([3, 3]), torch.float32)

In [36]:
a.device

device(type='cpu')

In [38]:
a.ndim, a.dim()

(2, 2)

In [40]:
a = torch.tensor([1, 2, 3, 4])
a[1], a[3]

(tensor(2), tensor(4))

In [41]:
a[0:3]

tensor([1, 2, 3])

In [42]:
a[a > 1]

tensor([2, 3, 4])

In [43]:
torch.where(a >= 2)

(tensor([1, 2, 3]),)

In [56]:
a = torch.rand((2, 2))

In [57]:
a

tensor([[0.2780, 0.3503],
        [0.5514, 0.1039]])

In [58]:
a.dtype

torch.float32

In [59]:
a.to(dtype=torch.int8)

tensor([[0, 0],
        [0, 0]], dtype=torch.int8)

In [60]:
a.to(dtype=torch.double)

tensor([[0.2780, 0.3503],
        [0.5514, 0.1039]], dtype=torch.float64)

In [61]:
a.int()

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)

In [62]:
a.float()

tensor([[0.2780, 0.3503],
        [0.5514, 0.1039]])

In [74]:
a = torch.rand((1000, 1000))
b = torch.rand((1000, 1000))

In [75]:
torch.matmul(a, b)

tensor([[253.8475, 258.6958, 257.3334,  ..., 264.1113, 253.9341, 262.3782],
        [253.7237, 257.6933, 249.3532,  ..., 257.3741, 253.2208, 253.0038],
        [251.5954, 251.0919, 251.1998,  ..., 254.0102, 248.6219, 254.4298],
        ...,
        [246.7472, 249.2085, 251.8767,  ..., 256.2102, 243.5616, 254.5831],
        [251.4218, 250.8581, 246.0346,  ..., 258.2057, 250.1922, 253.6920],
        [256.4836, 249.7865, 252.4814,  ..., 258.0119, 242.9774, 251.6231]])

In [76]:
torch.add(a, b), torch.sub(a, b)

(tensor([[0.4297, 0.9403, 1.3515,  ..., 0.8804, 1.6215, 1.1210],
         [1.1582, 0.4987, 1.6595,  ..., 1.9113, 1.3860, 0.8811],
         [0.7269, 1.0528, 0.4131,  ..., 1.3076, 0.5909, 0.9279],
         ...,
         [0.9517, 1.3992, 0.6971,  ..., 1.7444, 1.3987, 0.9529],
         [1.0284, 0.3314, 1.8106,  ..., 0.3934, 0.4550, 0.8201],
         [1.5871, 1.1279, 1.1734,  ..., 1.3051, 0.8913, 0.6013]]),
 tensor([[ 0.1526,  0.3409, -0.2823,  ...,  0.2247,  0.0935,  0.8593],
         [-0.8105, -0.3691, -0.2979,  ...,  0.0119, -0.1720, -0.6812],
         [ 0.6429, -0.0540, -0.3047,  ..., -0.2943, -0.5241,  0.1190],
         ...,
         [ 0.7567,  0.0615,  0.1477,  ..., -0.0565, -0.3287,  0.1573],
         [-0.2505, -0.2920, -0.1030,  ...,  0.3287,  0.0956, -0.4916],
         [ 0.2888,  0.5234, -0.0881,  ...,  0.1213,  0.4304,  0.3820]]))

In [77]:
a.dim()

2

In [80]:
a.flatten()

tensor([0.2911, 0.6406, 0.5346,  ..., 0.7132, 0.6608, 0.4917])

In [81]:
a.dim()

2

In [72]:
torch.dot(a, b)

tensor(70)

In [83]:
torch.linalg.det(a)

tensor(inf)

In [84]:
torch.tensor([1, 2, 3]) * 2

tensor([2, 4, 6])

In [86]:
list([1, 2, 3]) * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [97]:
a = torch.rand((2, 3))
a

tensor([[0.5718, 0.6820, 0.8363],
        [0.2856, 0.0468, 0.3866]])

In [98]:
torch.transpose(a, 1, 0)

tensor([[0.5718, 0.2856],
        [0.6820, 0.0468],
        [0.8363, 0.3866]])

In [99]:
a = torch.tensor([[1, 2, 3]])
a.dim()

2

In [100]:
b = a.squeeze()
b.ndim

1

In [104]:
arr = torch.randn(1, 2, 3)
arr.shape

torch.Size([1, 2, 3])

In [106]:
y = arr.squeeze(0)
y.shape

torch.Size([2, 3])

In [107]:
a = torch.rand((2, 3))

In [108]:
a.reshape(3, 2)

tensor([[0.5130, 0.3180],
        [0.7948, 0.2104],
        [0.6745, 0.2022]])

In [109]:
a.reshape(1, -1)

tensor([[0.5130, 0.3180, 0.7948, 0.2104, 0.6745, 0.2022]])